#!/usr/bin/env bash

if [ -z "${SERVER_NAME}" ]; then
  SERVER_NAME="localhost"
fi

export FACTER_SERVER_NAME="${SERVER_NAME}"

if [ -z "${BACKEND}" ]; then
  BACKEND="file"
fi

export FACTER_BACKEND="${BACKEND}"

if [ -z "${BACKEND_ADVERTISE_ADDR}" ]; then
  BACKEND_ADVERTISE_ADDR=""
fi

export FACTER_BACKEND_ADVERTISE_ADDR="${BACKEND_ADVERTISE_ADDR}"

if [ -z "${BACKEND_CONSUL_PATH}" ]; then
  BACKEND_CONSUL_PATH=""
fi

export FACTER_BACKEND_CONSUL_PATH="${BACKEND_CONSUL_PATH}"

if [ -z "${BACKEND_CONSUL_ADDRESS}" ]; then
  BACKEND_CONSUL_ADDRESS=""
fi

export FACTER_BACKEND_CONSUL_ADDRESS="${BACKEND_CONSUL_ADDRESS}"

if [ -z "${BACKEND_CONSUL_SCHEME}" ]; then
  BACKEND_CONSUL_SCHEME=""
fi

export FACTER_BACKEND_CONSUL_SCHEME="${BACKEND_CONSUL_SCHEME}"

if [ -z "${BACKEND_CONSUL_DATACENTER}" ]; then
  BACKEND_CONSUL_DATACENTER=""
fi

export FACTER_BACKEND_CONSUL_DATACENTER="${BACKEND_CONSUL_DATACENTER}"

if [ -z "${BACKEND_CONSUL_TOKEN}" ]; then
  BACKEND_CONSUL_TOKEN=""
fi

export FACTER_BACKEND_CONSUL_TOKEN="${BACKEND_CONSUL_TOKEN}"

if [ -z "${BACKEND_ZOOKEEPER_PATH}" ]; then
  BACKEND_ZOOKEEPER_PATH=""
fi

export FACTER_BACKEND_ZOOKEEPER_PATH="${BACKEND_ZOOKEEPER_PATH}"

if [ -z "${BACKEND_ZOOKEEPER_ADDRESS}" ]; then
  BACKEND_ZOOKEEPER_ADDRESS=""
fi

export FACTER_BACKEND_ZOOKEEPER_ADDRESS="${BACKEND_ZOOKEEPER_ADDRESS}"
